### ISSUE TITLE
Bug with command center

### ISSUE THREAD

**Issue by 1sandovalgerardo** [1sandovalgerardo/IMX#12]
JBI Scrap Processors <module 'imxUtilities.jobsite' from '/home/gsandoval/Documents/IMX/IMX/IMX/imxUtilities/jobsite.py'> 2022-02-14 2022-02-19
index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/home/gsandoval/Documents/IMX/IMX/IMX/imxUtilities/jobsite.py", line 247, in generate_invoice
    invoice_to_table(invoice_df, new_invoice_num, company)
  File "/home/gsandoval/Documents/IMX/IMX/IMX/imxUtilities/jobsite.py", line 261, in invoice_to_table
    job_site = invoice_data['Job Site'].unique()[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

there was an error

**Comment by 1sandovalgerardo** [comment]
Repaired.

**Comment by 1sandovalgerardo** [comment]
Bug Repaired
